/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShareRouteImport } from './routes/share'
import { Route as MeRouteImport } from './routes/me'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as FinaleRouteImport } from './routes/finale'
import { Route as CardRouteImport } from './routes/card'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartyIdRouteImport } from './routes/party.$id'
import { Route as ApiPublicSceneBuzzRouteImport } from './routes/api/public/scene-buzz'
import { Route as ApiPublicPersonalizeIntroRouteImport } from './routes/api/public/personalize-intro'
import { Route as ApiPublicPersonalizeCardRouteImport } from './routes/api/public/personalize-card'

const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const FinaleRoute = FinaleRouteImport.update({
  id: '/finale',
  path: '/finale',
  getParentRoute: () => rootRouteImport,
} as any)
const CardRoute = CardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyIdRoute = PartyIdRouteImport.update({
  id: '/party/$id',
  path: '/party/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSceneBuzzRoute = ApiPublicSceneBuzzRouteImport.update({
  id: '/api/public/scene-buzz',
  path: '/api/public/scene-buzz',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPersonalizeIntroRoute =
  ApiPublicPersonalizeIntroRouteImport.update({
    id: '/api/public/personalize-intro',
    path: '/api/public/personalize-intro',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPersonalizeCardRoute =
  ApiPublicPersonalizeCardRouteImport.update({
    id: '/api/public/personalize-card',
    path: '/api/public/personalize-card',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/card': typeof CardRoute
  '/finale': typeof FinaleRoute
  '/journey': typeof JourneyRoute
  '/library': typeof LibraryRoute
  '/me': typeof MeRoute
  '/share': typeof ShareRoute
  '/party/$id': typeof PartyIdRoute
  '/api/public/personalize-card': typeof ApiPublicPersonalizeCardRoute
  '/api/public/personalize-intro': typeof ApiPublicPersonalizeIntroRoute
  '/api/public/scene-buzz': typeof ApiPublicSceneBuzzRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/card': typeof CardRoute
  '/finale': typeof FinaleRoute
  '/journey': typeof JourneyRoute
  '/library': typeof LibraryRoute
  '/me': typeof MeRoute
  '/share': typeof ShareRoute
  '/party/$id': typeof PartyIdRoute
  '/api/public/personalize-card': typeof ApiPublicPersonalizeCardRoute
  '/api/public/personalize-intro': typeof ApiPublicPersonalizeIntroRoute
  '/api/public/scene-buzz': typeof ApiPublicSceneBuzzRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/card': typeof CardRoute
  '/finale': typeof FinaleRoute
  '/journey': typeof JourneyRoute
  '/library': typeof LibraryRoute
  '/me': typeof MeRoute
  '/share': typeof ShareRoute
  '/party/$id': typeof PartyIdRoute
  '/api/public/personalize-card': typeof ApiPublicPersonalizeCardRoute
  '/api/public/personalize-intro': typeof ApiPublicPersonalizeIntroRoute
  '/api/public/scene-buzz': typeof ApiPublicSceneBuzzRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/card'
    | '/finale'
    | '/journey'
    | '/library'
    | '/me'
    | '/share'
    | '/party/$id'
    | '/api/public/personalize-card'
    | '/api/public/personalize-intro'
    | '/api/public/scene-buzz'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/card'
    | '/finale'
    | '/journey'
    | '/library'
    | '/me'
    | '/share'
    | '/party/$id'
    | '/api/public/personalize-card'
    | '/api/public/personalize-intro'
    | '/api/public/scene-buzz'
  id:
    | '__root__'
    | '/'
    | '/card'
    | '/finale'
    | '/journey'
    | '/library'
    | '/me'
    | '/share'
    | '/party/$id'
    | '/api/public/personalize-card'
    | '/api/public/personalize-intro'
    | '/api/public/scene-buzz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardRoute: typeof CardRoute
  FinaleRoute: typeof FinaleRoute
  JourneyRoute: typeof JourneyRoute
  LibraryRoute: typeof LibraryRoute
  MeRoute: typeof MeRoute
  ShareRoute: typeof ShareRoute
  PartyIdRoute: typeof PartyIdRoute
  ApiPublicPersonalizeCardRoute: typeof ApiPublicPersonalizeCardRoute
  ApiPublicPersonalizeIntroRoute: typeof ApiPublicPersonalizeIntroRoute
  ApiPublicSceneBuzzRoute: typeof ApiPublicSceneBuzzRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finale': {
      id: '/finale'
      path: '/finale'
      fullPath: '/finale'
      preLoaderRoute: typeof FinaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/$id': {
      id: '/party/$id'
      path: '/party/$id'
      fullPath: '/party/$id'
      preLoaderRoute: typeof PartyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scene-buzz': {
      id: '/api/public/scene-buzz'
      path: '/api/public/scene-buzz'
      fullPath: '/api/public/scene-buzz'
      preLoaderRoute: typeof ApiPublicSceneBuzzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/personalize-intro': {
      id: '/api/public/personalize-intro'
      path: '/api/public/personalize-intro'
      fullPath: '/api/public/personalize-intro'
      preLoaderRoute: typeof ApiPublicPersonalizeIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/personalize-card': {
      id: '/api/public/personalize-card'
      path: '/api/public/personalize-card'
      fullPath: '/api/public/personalize-card'
      preLoaderRoute: typeof ApiPublicPersonalizeCardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardRoute: CardRoute,
  FinaleRoute: FinaleRoute,
  JourneyRoute: JourneyRoute,
  LibraryRoute: LibraryRoute,
  MeRoute: MeRoute,
  ShareRoute: ShareRoute,
  PartyIdRoute: PartyIdRoute,
  ApiPublicPersonalizeCardRoute: ApiPublicPersonalizeCardRoute,
  ApiPublicPersonalizeIntroRoute: ApiPublicPersonalizeIntroRoute,
  ApiPublicSceneBuzzRoute: ApiPublicSceneBuzzRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
